version: 2.1
orbs:
  docker: circleci/docker@1.7.0

jobs:
  login-ecr:
    machine: true
    resource_class: vishal-chavda/cicdrunner
    steps:
      - checkout
      - run:
          name: Configure AWS
          command: |
             echo $ACCESS_KEY >> ~/cred
             echo $SECRET_KEY >> ~/cred
             echo $REPO_URL >> ~/cred
#            echo "[default]" >> ~/.aws/credentials
#            echo "aws_access_key_id=$ACCESS_KEY" >> ~/.aws/credentials
#            echo "aws_secret_access_key=$SECRET_KEY" >> ~/.aws/credentials
#            echo "[default]" >> ~/.aws/config
#            echo "region=us-east-1" >> ~/.aws/config
      - run:
          name: Login to AWS ECR
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 496215038078.dkr.ecr.us-east-1.amazonaws.com

  build-docker-image:
    machine: true
    resource_class: vishal-chavda/cicdrunner
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t simpleapp .
            docker tag simpleapp:latest 496215038078.dkr.ecr.us-east-1.amazonaws.com/simpleapp:latest
          environment:
            REPO_URL: $REPO_URL

  push-docker-image:
    machine: true
    resource_class: vishal-chavda/cicdrunner
    steps:
      - checkout
      - run:
          name: Push Docker image to ECR
          command: docker push 496215038078.dkr.ecr.us-east-1.amazonaws.com/simpleapp:latest
          environment:
            REPO_URL: $REPO_URL

workflows:
  version: 2
  build-and-push:
    jobs:
      - login-ecr:
          context:
            - AWS            
      - build-docker-image:
          requires:
            - login-ecr
      - push-docker-image:
          requires:
            - build-docker-image
