version: 2.1
orbs:
  docker: circleci/docker@1.7.0

jobs:
  login-ecr:
    machine: true
    resource_class: vishal-chavda/cicdrunner
    steps:
      - checkout
      - run:
          name: Configure AWS
          command: |
            mkdir ~/.aws
            echo "[default]" >> ~/.aws/credentials
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
            echo "[default]" >> ~/.aws/config
            echo "region=us-east-1" >> ~/.aws/config
      - run:
          name: Login to AWS ECR
          command: |
            aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPO_URL

  build-docker-image:
    machine: true
    resource_class: vishal-chavda/cicdrunner
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t simpleapp .
            docker tag simpleapp:latest $REPO_URL/simpleapp:latest
          environment:
            REPO_URL: $REPO_URL

  push-docker-image:
    machine: true
    resource_class: vishal-chavda/cicdrunner
    steps:
      - checkout
      - run:
          name: Push Docker image to ECR
          command: docker push $REPO_URL/simpleapp:latest
          environment:
            REPO_URL: $REPO_URL

workflows:
  version: 2
  build-and-push:
    jobs:
      - login-ecr:
          context:
            ACCESS_KEY
            SECRET_KEY
            REPO_URL
      - build-docker-image:
          requires:
            - login-ecr
      - push-docker-image:
          requires:
            - build-docker-image
