version: 2.1
executors:
  default:
    working_directory: ~/app

jobs:
  dockerize:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: |
            docker build -t simpleapp:${CIRCLE_SHA1} .
