version: 2.1
orbs:
  docker: circleci/docker@1.7.0

jobs:
  login-ecr:
    machine: true
    resource_class: vishal-chavda/cicdrunner
    steps:
      - checkout
      - run:
          name: Configure AWS
          command: |
            mkdir -p /tmp/workspace
            echo "export REPO_URL=\"$REPO_URL2\"" >> /tmp/workspace/env_vars
            mkdir ~/.aws
            aws configure set aws_access_key_id $ACCESS_KEY
            aws configure set aws_secret_access_key $SECRET_KEY
            aws configure set default.region us-east-1
      - run:
          name: Login to AWS ECR
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPO_URL
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - /tmp/workspace/env_vars
      
  build-docker-image:
    machine: true
    resource_class: vishal-chavda/cicdrunner
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: |
            source /tmp/workspace/env_vars
            echo "$REPO_URL" > ~/testvar
      - checkout
      - run:
          name: Build Docker image
          command: |
            echo $REPO_URL > ~/repo
            docker build -t simpleapp .
            docker tag simpleapp:latest $REPO_URL/simpleapp:latest

  push-docker-image:
    machine: true
    resource_class: vishal-chavda/cicdrunner
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: |
            source /tmp/workspace/env_vars
            echo "$REPO_URL" >> ~/testvar
      - checkout
      - run:
          name: Push Docker image to ECR
          command: docker push $REPO_URL/simpleapp:latest

  cleanup:
    machine: true
    resource_class: vishal-chavda/cicdrunner
    steps:
      - checkout
      - run:
          name: Remove AWS credentials and Docker image
          command: |
            rm -rf ~/.aws
            docker rmi simpleapp $REPO_URL/simpleapp:latest -f
          
workflows:
  version: 2
  build-and-push:
    jobs:
      - login-ecr:
          context:
            - AWS            
      - build-docker-image:
          requires:
            - login-ecr
      - push-docker-image:
          requires:
            - build-docker-image
      - cleanup:
          requires:
            - push-docker-image
